#pragma once

#include <poppler/qt6/poppler-qt6.h>
#include <QImage>
#include <QPixmap>
#include <QSizeF>
#include <QRectF>
#include <QSharedPointer>
#include <QMutex>
#include <memory>
#include "../utils/ErrorHandling.h"
#include "../logging/Logger.h"

/**
 * @brief Safe PDF rendering utilities with defensive programming and Qt PDF compatibility handling
 *
 * This class provides safe wrappers around Poppler's renderToImage() function to prevent
 * segmentation faults when dealing with Qt-generated PDFs (created with QPdfWriter).
 * Qt-generated PDFs can cause crashes in libpoppler-qt6-3.dll due to compatibility issues.
 */
class SafePDFRenderer {
public:
    /**
     * @brief Result of PDF compatibility detection
     */
    enum class CompatibilityResult {
        Compatible,         ///< PDF should render safely with Poppler
        QtGenerated,        ///< PDF was likely generated by Qt (QPdfWriter) - high risk
        Corrupted,          ///< PDF appears corrupted
        Unknown             ///< Unable to determine compatibility
    };

    /**
     * @brief Rendering fallback strategy
     */
    enum class FallbackStrategy {
        Fail,               ///< Fail immediately if rendering fails
        UsePlaceholder,     ///< Use a placeholder image when rendering fails
        TryLowResolution,   ///< Try rendering at lower resolution as fallback
        RetryWithLimits     ///< Retry with conservative settings
    };

    /**
     * @brief Configuration for safe rendering operations
     */
    struct RenderConfig {
        double maxDPI = 300.0;              ///< Maximum DPI to prevent excessive memory usage
        double fallbackDPI = 72.0;          ///< DPI to use for fallback rendering
        int maxRetries = 2;                 ///< Maximum retry attempts
        bool enableCompatibilityCheck = true;  ///< Check PDF compatibility before rendering
        FallbackStrategy fallbackStrategy = FallbackStrategy::TryLowResolution;
        int timeoutMs = 5000;               ///< Timeout for rendering operations
        QSize maxImageSize = QSize(4000, 4000); ///< Maximum image size to prevent memory issues

        RenderConfig() = default;
    };

    /**
     * @brief Information about a rendering operation
     */
    struct RenderInfo {
        bool success = false;
        CompatibilityResult compatibility = CompatibilityResult::Unknown;
        QString errorMessage;
        int attemptCount = 0;
        double actualDPI = 0.0;
        QSize renderedSize;
        bool usedFallback = false;
        qint64 renderTimeMs = 0;
    };

    /**
     * @brief Static singleton access
     */
    static SafePDFRenderer& instance();

    /**
     * @brief Set global rendering configuration
     * @param config Configuration to apply
     */
    void setRenderConfig(const RenderConfig& config);

    /**
     * @brief Get current rendering configuration
     * @return Current configuration
     */
    const RenderConfig& getRenderConfig() const;

    /**
     * @brief Safely render a PDF page to image with comprehensive error handling
     * @param page Poppler page to render
     * @param dpi Rendering DPI
     * @param info Optional output parameter for render information
     * @return Rendered image, or null image if rendering fails
     */
    QImage safeRenderPage(Poppler::Page* page, double dpi, RenderInfo* info = nullptr);

    /**
     * @brief Safely render a PDF page to pixmap
     * @param page Poppler page to render
     * @param dpi Rendering DPI
     * @param info Optional output parameter for render information
     * @return Rendered pixmap, or null pixmap if rendering fails
     */
    QPixmap safeRenderPageToPixmap(Poppler::Page* page, double dpi, RenderInfo* info = nullptr);

    /**
     * @brief Safely render a portion of a PDF page
     * @param page Poppler page to render
     * @param region Region to render (in page coordinates)
     * @param dpi Rendering DPI
     * @param info Optional output parameter for render information
     * @return Rendered image, or null image if rendering fails
     */
    QImage safeRenderPageRegion(Poppler::Page* page, const QRectF& region, double dpi, RenderInfo* info = nullptr);

    /**
     * @brief Check PDF compatibility to detect Qt-generated PDFs
     * @param document Poppler document to check
     * @return Compatibility assessment result
     */
    CompatibilityResult checkCompatibility(Poppler::Document* document);

    /**
     * @brief Check page compatibility to detect problematic pages
     * @param page Poppler page to check
     * @return Compatibility assessment result
     */
    CompatibilityResult checkPageCompatibility(Poppler::Page* page);

    /**
     * @brief Create a placeholder image for failed rendering
     * @param size Desired image size
     * @param text Optional text to include in placeholder
     * @return Placeholder image
     */
    QImage createPlaceholderImage(const QSize& size, const QString& text = QString());

    /**
     * @brief Test if a PDF page can be rendered safely
     * @param page Poppler page to test
     * @param info Optional output parameter for test information
     * @return True if page can likely be rendered without crashes
     */
    bool canRenderSafely(Poppler::Page* page, RenderInfo* info = nullptr);

    /**
     * @brief Get statistics about rendering operations
     * @return Map with rendering statistics
     */
    QVariantMap getStatistics() const;

    /**
     * @brief Reset rendering statistics
     */
    void resetStatistics();

private:
    SafePDFRenderer() = default;
    ~SafePDFRenderer() = default;
    SafePDFRenderer(const SafePDFRenderer&) = delete;
    SafePDFRenderer& operator=(const SafePDFRenderer&) = delete;

    /**
     * @brief Internal safe rendering implementation
     */
    QImage safeRenderPageInternal(Poppler::Page* page, double dpi, const QRectF& region, RenderInfo* info);

    /**
     * @brief Try rendering with low DPI as fallback
     */
    QImage tryLowDpiRender(Poppler::Page* page, const QRectF& region, RenderInfo* info);

    /**
     * @brief Check if DPI is within safe limits
     */
    bool isSafeDPI(double dpi) const;

    /**
     * @brief Check if image size is within safe limits
     */
    bool isSafeImageSize(const QSize& size) const;

    /**
     * @brief Validate page before rendering
     */
    bool validatePage(Poppler::Page* page);

    /**
     * @brief Extract PDF metadata for compatibility checking
     */
    QString extractPDFMetadata(Poppler::Document* document);

    /**
     * @brief Check if PDF was likely created by QPdfWriter
     */
    bool isQtGeneratedPDF(Poppler::Document* document);

    /**
     * @brief Check if page contains Qt-specific content
     */
    bool hasQtSpecificContent(Poppler::Page* page);

    /**
     * @brief Thread-safe rendering operation
     */
    QImage threadSafeRender(Poppler::Page* page, double dpi, const QRectF& region);

    mutable QMutex m_mutex;
    RenderConfig m_config;

    // Statistics
    mutable QMutex m_statsMutex;
    QVariantMap m_statistics;
};

/**
 * @brief Convenience functions for safe PDF rendering
 */
namespace SafePDFRendering {
    /**
     * @brief Quick safe render with default configuration
     */
    inline QImage renderPage(Poppler::Page* page, double dpi = 150.0) {
        return SafePDFRenderer::instance().safeRenderPage(page, dpi);
    }

    /**
     * @brief Quick safe render to pixmap
     */
    inline QPixmap renderPageToPixmap(Poppler::Page* page, double dpi = 150.0) {
        return SafePDFRenderer::instance().safeRenderPageToPixmap(page, dpi);
    }

    /**
     * @brief Check if document is safe to render
     */
    inline bool isSafeToRender(Poppler::Document* document) {
        SafePDFRenderer::CompatibilityResult result =
            SafePDFRenderer::instance().checkCompatibility(document);
        return result != SafePDFRenderer::CompatibilityResult::QtGenerated &&
               result != SafePDFRenderer::CompatibilityResult::Corrupted;
    }

    /**
     * @brief Get appropriate DPI for document type
     */
    inline double getSafeDPI(Poppler::Document* document, double requestedDPI) {
        SafePDFRenderer::CompatibilityResult result =
            SafePDFRenderer::instance().checkCompatibility(document);

        if (result == SafePDFRenderer::CompatibilityResult::QtGenerated) {
            return qMin(requestedDPI, 72.0);  // Use low DPI for Qt PDFs
        }

        return qMin(requestedDPI, 300.0);  // Standard limit
    }
}