#!/bin/bash
# Unified clangd configuration script for SAST Readium
# Updates .clangd configuration file with the correct CompilationDatabase path
# Supports all platforms with simplified preset system

set -e

# Default values
BUILD_DIR=""
AUTO_MODE=false
LIST_MODE=false
VERBOSE=false
FORCE=false

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CLANGD_FILE="$PROJECT_ROOT/.clangd"

# Simplified build directories from the new preset system
POSSIBLE_BUILD_DIRS=(
    "build/Debug-Unix"
    "build/Release-Unix"
    "build/Debug-Windows"
    "build/Release-Windows"
    "build/Debug-MSYS2"
    "build/Release-MSYS2"
)

# Function to print usage
show_usage() {
    cat << EOF
Usage: $0 [BUILD_DIR] [OPTIONS]

Updates .clangd configuration with the correct CompilationDatabase path.

Arguments:
  BUILD_DIR         Build directory relative to project root (e.g., build/Debug-Unix)

Options:
  --auto           Auto-detect the most recent build directory
  --list           List all possible build directories
  --verbose        Enable verbose output
  --force          Force update even if compile_commands.json doesn't exist
  --help           Show this help message

Examples:
  $0 build/Debug-Unix                    # Use specific build directory
  $0 --auto                              # Auto-detect build directory
  $0 --list                              # List available build directories

Simplified Build Presets:
  Debug-Unix / Release-Unix              # Linux/macOS with system packages
  Debug-Windows / Release-Windows        # Windows with vcpkg
  Debug-MSYS2 / Release-MSYS2           # Windows MSYS2 with system packages
EOF
}

# Function to log messages
log() {
    local level="$1"
    local message="$2"
    if [[ "$VERBOSE" == "true" || "$level" == "ERROR" ]]; then
        echo "[$level] $message" >&2
    fi
}

# Function to list available build directories
list_build_dirs() {
    echo "Available build directories:"
    for dir in "${POSSIBLE_BUILD_DIRS[@]}"; do
        local full_path="$PROJECT_ROOT/$dir"
        local compile_commands="$full_path/compile_commands.json"
        if [[ -d "$full_path" ]]; then
            if [[ -f "$compile_commands" ]]; then
                echo "  ✅ $dir (compile_commands.json found)"
            else
                echo "  ⚠️  $dir (directory exists, no compile_commands.json)"
            fi
        else
            echo "  ❌ $dir (directory not found)"
        fi
    done
}

# Function to auto-detect build directory
auto_detect_build_dir() {
    log "INFO" "Auto-detecting build directory..."
    
    local best_dir=""
    local best_time=0
    
    for dir in "${POSSIBLE_BUILD_DIRS[@]}"; do
        local full_path="$PROJECT_ROOT/$dir"
        local compile_commands="$full_path/compile_commands.json"
        
        if [[ -f "$compile_commands" ]]; then
            local mod_time
            if [[ "$OSTYPE" == "darwin"* ]]; then
                mod_time=$(stat -f %m "$compile_commands" 2>/dev/null || echo 0)
            else
                mod_time=$(stat -c %Y "$compile_commands" 2>/dev/null || echo 0)
            fi
            
            if [[ $mod_time -gt $best_time ]]; then
                best_time=$mod_time
                best_dir="$dir"
            fi
        fi
    done
    
    if [[ -n "$best_dir" ]]; then
        log "INFO" "Auto-detected build directory: $best_dir"
        echo "$best_dir"
    else
        log "ERROR" "No build directory with compile_commands.json found"
        return 1
    fi
}

# Function to update .clangd file
update_clangd_config() {
    local build_dir="$1"
    local full_build_path="$PROJECT_ROOT/$build_dir"
    local compile_commands="$full_build_path/compile_commands.json"
    
    # Validate build directory
    if [[ ! -d "$full_build_path" ]]; then
        log "ERROR" "Build directory does not exist: $build_dir"
        return 1
    fi
    
    if [[ ! -f "$compile_commands" && "$FORCE" != "true" ]]; then
        log "ERROR" "compile_commands.json not found in $build_dir"
        log "INFO" "Run cmake configuration first or use --force to override"
        return 1
    fi
    
    # Create .clangd configuration
    log "INFO" "Updating .clangd configuration for build directory: $build_dir"
    
    cat > "$CLANGD_FILE" << EOF
# clangd configuration for SAST Readium
# Auto-generated by scripts/clangd-config.sh
# Build directory: $build_dir

CompileFlags:
  Add:
    - -std=c++20
    - -Wall
    - -Wextra
  Remove:
    - -W*
    - -fcoroutines-ts
  CompilationDatabase: $build_dir

Index:
  Background: Build
  StandardLibrary: Yes

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes

Diagnostics:
  ClangTidy:
    Add:
      - readability-*
      - modernize-*
      - performance-*
    Remove:
      - readability-magic-numbers
      - modernize-use-trailing-return-type

# Simplified build system configuration
# Generated: $(date)
EOF
    
    log "INFO" "Successfully updated $CLANGD_FILE"
    log "INFO" "Restart your language server to apply changes"
    
    return 0
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --auto)
            AUTO_MODE=true
            shift
            ;;
        --list)
            LIST_MODE=true
            shift
            ;;
        --verbose)
            VERBOSE=true
            shift
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --help)
            show_usage
            exit 0
            ;;
        -*)
            log "ERROR" "Unknown option: $1"
            show_usage
            exit 1
            ;;
        *)
            if [[ -z "$BUILD_DIR" ]]; then
                BUILD_DIR="$1"
            else
                log "ERROR" "Multiple build directories specified"
                show_usage
                exit 1
            fi
            shift
            ;;
    esac
done

# Main logic
if [[ "$LIST_MODE" == "true" ]]; then
    list_build_dirs
    exit 0
fi

if [[ "$AUTO_MODE" == "true" ]]; then
    BUILD_DIR=$(auto_detect_build_dir)
    if [[ $? -ne 0 ]]; then
        exit 1
    fi
fi

if [[ -z "$BUILD_DIR" ]]; then
    log "ERROR" "No build directory specified"
    show_usage
    exit 1
fi

# Update clangd configuration
update_clangd_config "$BUILD_DIR"
exit $?
