#!/usr/bin/env pwsh
# Generate WiX manifest from installation directory
# This script scans the installation directory and generates a complete WiX source file

param(
    [Parameter(Mandatory=$true)]
    [string]$InstallDir,

    [Parameter(Mandatory=$false)]
    [string]$OutputFile = "AutoGenerated.wxs",

    [Parameter(Mandatory=$false)]
    [string]$SourceDir = ".",

    [switch]$Verbose
)

$ErrorActionPreference = "Stop"

# Logging
function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = switch ($Level) {
        "ERROR" { "Red" }
        "WARN"  { "Yellow" }
        "SUCCESS" { "Green" }
        default { "White" }
    }
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $color
}

# Validate installation directory
if (-not (Test-Path $InstallDir)) {
    Write-Log "Installation directory not found: $InstallDir" "ERROR"
    exit 1
}

Write-Log "Scanning installation directory: $InstallDir"

# Generate GUID
function New-ComponentGuid {
    param([string]$Seed)
    # Generate deterministic GUID based on seed
    $md5 = [System.Security.Cryptography.MD5]::Create()
    $hash = $md5.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Seed))
    $guid = [System.Guid]::new($hash)
    return $guid.ToString().ToUpper()
}

# Collect files
$binDir = Join-Path $InstallDir "bin"
if (-not (Test-Path $binDir)) {
    Write-Log "Bin directory not found: $binDir" "ERROR"
    exit 1
}

$allFiles = Get-ChildItem -Path $binDir -Recurse -File
Write-Log "Found $($allFiles.Count) files"

# Categorize files
$categories = @{
    Executables = @()
    QtCore = @()
    QtPlugins = @()
    AppLibraries = @()
    ThirdParty = @()
    Resources = @()
}

foreach ($file in $allFiles) {
    $relativePath = $file.FullName.Substring($binDir.Length + 1)
    $category = "Resources"

    if ($file.Extension -eq ".exe") {
        $category = "Executables"
    }
    elseif ($file.Name -match "^Qt6.*\.dll$") {
        $category = "QtCore"
    }
    elseif ($relativePath -match "^(platforms|imageformats|iconengines|styles|tls)\\") {
        $category = "QtPlugins"
    }
    elseif ($file.Name -match "^ElaWidgetTools\.dll$") {
        $category = "AppLibraries"
    }
    elseif ($file.Extension -eq ".dll") {
        $category = "ThirdParty"
    }

    $categories[$category] += $file
}

# Log categorization
foreach ($category in $categories.Keys) {
    $count = $categories[$category].Count
    Write-Log "${category}: $count files"
}

# Generate WiX XML
$xmlContent = '<?xml version="1.0" encoding="UTF-8"?>' + "`n"
$xmlContent += '<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">' + "`n"
$xmlContent += '  <!-- Auto-generated file list -->' + "`n"
$xmlContent += '  <Fragment>' + "`n"
$xmlContent += '    <ComponentGroup Id="AutoGeneratedFiles" Directory="BinFolder">' + "`n"

# Generate components
$componentId = 1
foreach ($file in $allFiles) {
    $relativePath = $file.FullName.Substring($binDir.Length + 1)
    $guid = New-ComponentGuid -Seed $relativePath

    $xmlContent += "      <Component Id=`"AutoComp$componentId`" Guid=`"$guid`">`n"
    $xmlContent += "        <File Id=`"AutoFile$componentId`" Source=`"`$(var.InstallDir)\bin\$relativePath`" KeyPath=`"yes`" />`n"
    $xmlContent += "      </Component>`n"

    $componentId++
}

$xmlContent += '    </ComponentGroup>' + "`n"
$xmlContent += '  </Fragment>' + "`n"
$xmlContent += '</Wix>' + "`n"

# Write to file
$xmlContent | Out-File -FilePath $OutputFile -Encoding UTF8

Write-Log "WiX manifest generated: $OutputFile" "SUCCESS"
Write-Log "Total components: $($componentId - 1)"
Write-Log "Use this as a reference for completing Product.wxs"
