#!/usr/bin/env pwsh
# Unified clangd configuration script for SAST Readium
# Updates .clangd configuration file with the correct CompilationDatabase path
# Cross-platform PowerShell script for simplified preset system

param(
    [string]$BuildDir = "",
    [switch]$Auto,
    [switch]$List,
    [switch]$Verbose,
    [switch]$Force,
    [switch]$Help
)

$ProjectRoot = Split-Path -Parent $PSScriptRoot
$ClangdFile = Join-Path $ProjectRoot ".clangd"

# Simplified build directories from the new preset system
$PossibleBuildDirs = @(
    "build/Debug-Unix",
    "build/Release-Unix",
    "build/Debug-Windows",
    "build/Release-Windows",
    "build/Debug-MSYS2",
    "build/Release-MSYS2"
)

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    if ($Verbose -or $Level -eq "ERROR") {
        Write-Host "[$Level] $Message" -ForegroundColor $(if ($Level -eq "ERROR") { "Red" } else { "Green" })
    }
}

function Show-Usage {
    @"
Usage: .\clangd-config.ps1 [BuildDir] [OPTIONS]

Updates .clangd configuration with the correct CompilationDatabase path.

Parameters:
  -BuildDir         Build directory relative to project root (e.g., build/Debug-Windows)
  -Auto            Auto-detect the most recent build directory
  -List            List all possible build directories
  -Verbose         Enable verbose output
  -Force           Force update even if compile_commands.json doesn't exist
  -Help            Show this help message

Examples:
  .\clangd-config.ps1 -BuildDir build/Debug-Windows    # Use specific build directory
  .\clangd-config.ps1 -Auto                            # Auto-detect build directory
  .\clangd-config.ps1 -List                            # List available build directories

Simplified Build Presets:
  Debug-Unix / Release-Unix              # Linux/macOS with system packages
  Debug-Windows / Release-Windows        # Windows with vcpkg
  Debug-MSYS2 / Release-MSYS2           # Windows MSYS2 with system packages
"@
}

function Get-BuildDirectories {
    Write-Host "Available build directories:"
    foreach ($dir in $PossibleBuildDirs) {
        $fullPath = Join-Path $ProjectRoot $dir
        $compileCommands = Join-Path $fullPath "compile_commands.json"

        if (Test-Path $fullPath -PathType Container) {
            if (Test-Path $compileCommands -PathType Leaf) {
                Write-Host "  ✅ $dir (compile_commands.json found)" -ForegroundColor Green
            } else {
                Write-Host "  ⚠️  $dir (directory exists, no compile_commands.json)" -ForegroundColor Yellow
            }
        } else {
            Write-Host "  ❌ $dir (directory not found)" -ForegroundColor Red
        }
    }
}

function Find-LatestBuildDir {
    Write-Log "Auto-detecting build directory..." "INFO"

    $bestDir = ""
    $bestTime = [DateTime]::MinValue

    foreach ($dir in $PossibleBuildDirs) {
        $fullPath = Join-Path $ProjectRoot $dir
        $compileCommands = Join-Path $fullPath "compile_commands.json"

        if (Test-Path $compileCommands -PathType Leaf) {
            $modTime = (Get-Item $compileCommands).LastWriteTime
            if ($modTime -gt $bestTime) {
                $bestTime = $modTime
                $bestDir = $dir
            }
        }
    }

    if ($bestDir) {
        Write-Log "Auto-detected build directory: $bestDir" "INFO"
        return $bestDir
    } else {
        Write-Log "No build directory with compile_commands.json found" "ERROR"
        return $null
    }
}

function Update-ClangdConfig {
    param([string]$BuildDirectory)

    $fullBuildPath = Join-Path $ProjectRoot $BuildDirectory
    $compileCommands = Join-Path $fullBuildPath "compile_commands.json"

    # Validate build directory
    if (-not (Test-Path $fullBuildPath -PathType Container)) {
        Write-Log "Build directory does not exist: $BuildDirectory" "ERROR"
        return $false
    }

    if (-not (Test-Path $compileCommands -PathType Leaf) -and -not $Force) {
        Write-Log "compile_commands.json not found in $BuildDirectory" "ERROR"
        Write-Log "Run cmake configuration first or use -Force to override" "INFO"
        return $false
    }

    # Create .clangd configuration
    Write-Log "Updating .clangd configuration for build directory: $BuildDirectory" "INFO"

    $clangdContent = @"
# clangd configuration for SAST Readium
# Auto-generated by scripts/clangd-config.ps1
# Build directory: $BuildDirectory

CompileFlags:
  Add:
    - -std=c++20
    - -Wall
    - -Wextra
  Remove:
    - -W*
    - -fcoroutines-ts
  CompilationDatabase: $($BuildDirectory -replace '\\', '/')

Index:
  Background: Build
  StandardLibrary: Yes

InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes

Diagnostics:
  ClangTidy:
    Add:
      - readability-*
      - modernize-*
      - performance-*
    Remove:
      - readability-magic-numbers
      - modernize-use-trailing-return-type

# Simplified build system configuration
# Generated: $(Get-Date)
"@

    try {
        $clangdContent | Out-File -FilePath $ClangdFile -Encoding UTF8
        Write-Log "Successfully updated $ClangdFile" "INFO"
        Write-Log "Restart your language server to apply changes" "INFO"
        return $true
    } catch {
        Write-Log "Failed to write .clangd file: $($_.Exception.Message)" "ERROR"
        return $false
    }
}

# Main logic
if ($Help) {
    Show-Usage
    exit 0
}

if ($List) {
    Get-BuildDirectories
    exit 0
}

if ($Auto) {
    $BuildDir = Find-LatestBuildDir
    if (-not $BuildDir) {
        exit 1
    }
}

if (-not $BuildDir) {
    Write-Log "No build directory specified" "ERROR"
    Show-Usage
    exit 1
}

# Update clangd configuration
$success = Update-ClangdConfig $BuildDir
exit $(if ($success) { 0 } else { 1 })
